### ISSUE TITLE
model_trt.engine

### ISSUE THREAD

**Issue by Wang-Minxin** [ChenJiahao031008/EAO-Fusion#1]
您好，最近在复现您改进后的EAO-SLAM，请问其中的model_trt.engine如何获得？

**Comment by ChenJiahao031008** [comment]
这个文件是YOLOX采用TensorRT部署后生成的文件，YOLOX官方提供了转换代码，可以参考https://zhuanlan.zhihu.com/p/392570215这个进行部署
